### ISSUE TITLE
Error while importing a MSL file (import.py)

### ISSUE THREAD

**Issue by danield5732** [KIKIRPA/GCMStoolbox#5]
Hello,
I'm trying to use your tool, but stuck getting started.
Import this file [dd_190410_10.txt](https://github.com/KIKIRPA/GCMStoolbox/files/4595543/dd_190410_10.txt) (had to be renamed from .msl to .txt to upload to github) throws the following error:
`ValueError: invalid literal for int() with base 10: '36.0'`

The file was generated using OpenChrom, not sure if this might be an issue.

Can you offer any help on this? - Thanks a lot!

**Comment by danield5732** [comment]
I could solve the problem by changeing the first line argument to 'NAME'.
But now, the created json file seems not to contain any data: 
[gcmstoolbox.txt](https://github.com/KIKIRPA/GCMStoolbox/files/4595658/gcmstoolbox.txt) (again had to change .json to .txt for upload to github)

**Comment by kobbejager** [comment]
Hi.
The problem seems that OpenChrom exports the mass spectra as non-integer numericals. I've created a git branch "openchrom" with a fixed import-script (https://github.com/KIKIRPA/GCMStoolbox/tree/openchrom). Could you give this a try?

However, I don't understand what you mean with "changeing the first line argument to NAME"?

**Comment by danield5732** [comment]
Wow, thank you for the very fast fix! :-D
It seems to work pretty well well. I'm going to test it further..

What I ment by the "argument NAME" ist in line 186:
`if line.casefold().startswith('name'):`
Since 'name' is case sensitive it didn't matched with NAME in my MSL file. 
Anyhow, your fix works also with 'name'.

Thanks a lot!
